### ISSUE TITLE
TestPodDeploysContainerImage is failing

### ISSUE THREAD

**Issue by gisaf16** [gruntwork-io/terratest-helm-testing-example#2]
Trying to figure out how "-n" argument is being passed. New to Go lang

**Comment by yorinasub17** [comment]
Are you by chance using helm 3? If so, this hasn't been updated yet (will be updating this week). Please stand by...

**Comment by gisaf16** [comment]
Using helm 3, thanks @yorinasub17

**Comment by yorinasub17** [comment]
The helm v3 compatible PR is open now. You can check out the branch to try it out: ~https://github.com/gruntwork-io/terratest-helm-testing-example/tree/yori-helm3~ This is now in master!

**Comment by gisaf16** [comment]
Thanks for quickly updating to work with Helm 3!
