### ISSUE TITLE
Minimal pod template test failing

### ISSUE THREAD

**Issue by gisaf16** [gruntwork-io/terratest-helm-testing-example#4]
This is the error I am getting
Error: could not find template templates/pod.yaml in chart

This test was passing fine before today. Any insights on what might be the issue?

Much appreciated!

**Comment by gisaf16** [comment]
Using **output := helm.RenderTemplate(t, options, helmChartPath, "pod", []string{})**

seems to fix the issue

**Comment by yorinasub17** [comment]
Yup we just upgraded terratest to the latest, and in the newer versions the release name is required for rendering the template.

**Comment by gisaf16** [comment]
@yorinasub17 if I try to run it as is 
**helm.RenderTemplate(t, options, helmChartPath, "pod", []string{"templates/pod.yaml"}**

it fails, doesn't like that I specify the yaml file

**Comment by yorinasub17** [comment]
Which version of helm are you using and can you share the entire logs of the test output?

**Comment by yorinasub17** [comment]
FWIW, I am using the latest master, helm v3.1.1, go 1.13.8, and here are the logs:

```
%~> go test -v -run TestPodTemplateRendersContainerImage .                                                                                                [0]
=== RUN   TestPodTemplateRendersContainerImage
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:87: Running command helm with args [template --set image=nginx:1.15.8 --show-only templates/pod.yaml pod ../charts/minimal-pod]
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158: ---
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158: # Source: minimal-pod/templates/pod.yaml
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158: apiVersion: v1
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158: kind: Pod
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158: metadata:
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158:   name: pod-minimal-pod
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158:   labels:
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158:     app.kubernetes.io/name: minimal-pod
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158:     helm.sh/chart: minimal-pod-0.1.0
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158:     app.kubernetes.io/instance: pod
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158:     app.kubernetes.io/managed-by: Helm
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158: spec:
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158:   containers:
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158:     - name: minimal-pod
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158:       image: "nginx:1.15.8"
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158:       ports:
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158:         - name: http
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158:           containerPort: 80
TestPodTemplateRendersContainerImage 2020-03-03T07:49:07-08:00 command.go:158:           protocol: TCP
--- PASS: TestPodTemplateRendersContainerImage (0.08s)
PASS
ok      github.com/gruntwork-io/terratest-helm-testing-example/test     0.714s
```

**Comment by gisaf16** [comment]
These are my logs

C:\Development\terratest-helm-testing-example\test>go test -v -run TestPodTemplateRendersContainerImage
=== RUN   TestPodTemplateRendersContainerImage
--- FAIL: TestPodTemplateRendersContainerImage (0.00s)
    template.go:20:
                Error Trace:    template.go:20
                                                        minimal_pod_template_test.go:22
                Error:          Received unexpected error:
                                Could not resolve template file pod.yaml relative to chart path C:\Development\terratest-helm-testing-example\charts\minimal-pod
                Test:           TestPodTemplateRendersContainerImage
FAIL
exit status 1
FAIL    github.com/gruntwork-io/terratest-helm-testing-example/test     2.524s

**Comment by gisaf16** [comment]
@yorinasub17  these are my logs

C:\Development\terratest-helm-testing-example\test>go test minimal_pod_template_test.go
TestPodTemplateRendersContainerImage 2020-03-03T11:22:46-05:00 command.go:87: Running command helm with args [template --set image=nginx:1.15.8 --show-only templates/pod.yaml pod ../charts/minimal-pod]
TestPodTemplateRendersContainerImage 2020-03-03T11:22:47-05:00 command.go:158: Error: could not find template templates/pod.yaml in chart
--- FAIL: TestPodTemplateRendersContainerImage (0.94s)
    template.go:20:
                Error Trace:    template.go:20
                                                        minimal_pod_template_test.go:22
                Error:          Received unexpected error:
                                exit status 1
                Test:           TestPodTemplateRendersContainerImage
FAIL


**Using the same versions (helm and Go)

C:\Development\terratest-helm-testing-example\test>helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}**

**Comment by yorinasub17** [comment]
Does it work if you switch `templates/pod.yaml` to `templates\pod.yaml`, so it is a windows path? If not, I'll have to set up my windows box to investigate, but a bit buried at the moment so may not get to this anytime soon.

**Comment by gisaf16** [comment]
@yorinasub17  thanks, that was the issue!

**Comment by yorinasub17** [comment]
Glad it was that simple!

**Comment by nikitaverma04** [comment]
=== RUN   TestPodTemplateRendersContainerImage
TestPodTemplateRendersContainerImage 2020-04-07T05:23:22Z command.go:87: Running command helm with args [template --set image=nginx:1.15.8 --show-only templates/pod.yaml pod ../charts/minimal-pod]
TestPodTemplateRendersContainerImage 2020-04-07T05:23:22Z command.go:158: Error: unknown flag: --show-only
    TestPodTemplateRendersContainerImage: template.go:20:
                Error Trace:    template.go:20
                                                        minimal_pod_template_test.go:22
                Error:          Received unexpected error:
                                exit status 1
                Test:           TestPodTemplateRendersContainerImage
--- FAIL: TestPodTemplateRendersContainerImage (0.06s)
FAIL
FAIL    github.com/gruntwork-io/terratest-helm-testing-example/test     0.457s

**Comment by nikitaverma04** [comment]
Can anyone knows how to fix this ?

**Comment by gisaf16** [comment]
What version of helm are you using?
________________________________
