### ISSUE TITLE
issues running the test cases given in the repo

### ISSUE THREAD

**Issue by KNSailaja** [gruntwork-io/terratest-helm-testing-example#6]
Sorry, opening a new issue for reaching out to you

Hi, I have cloned helm testing repository and had all the pre requisites installed. I see the below errors when executing go test -v

Is there anything i am missing here? just followed the instructions in read me file

TestPodTemplateRendersContainerImage 2020-08-11T18:22:04+01:00 command.go:87: Running command helm with args [template --set image=nginx:1.15.8 --show-only templates/pod.yaml pod ../charts/minimal-pod]
TestPodTemplateRendersContainerImage 2020-08-11T18:22:04+01:00 command.go:158: _### Error: unknown flag: --show-only**_**
template.go:20:
Error Trace: template.go:20
minimal_pod_template_test.go:22
Error: Received unexpected error:
exit status 1
Test: TestPodTemplateRendersContainerImage

TestPodDeploysContainerImage 2020-08-11T18:22:04+01:00 command.go:158: Error: release: "nginx-v46mkh" not found
delete.go:12:
Error Trace: delete.go:12
panic.go:617
testing.go:698
install.go:16
minimal_pod_integration_test.go:39
Error: Received unexpected error:
exit status 1
Test: TestPodDeploysContainerImage
--- FAIL: TestPodDeploysContainerImage (1.62s)
=== RUN TestPodTemplateRendersContainerImage

3.TestPodDeploysContainerImage 2020-08-11T18:22:03+01:00 command.go:158: Error: This command needs 1 argument: chart name
install.go:16:
Error Trace: install.go:16
minimal_pod_integration_test.go:39
Error: Received unexpected error:
exit status 1
Test: TestPodDeploysContainerImage
TestPodDeploysContainerImage 2020-08-11T18:22:03+01:00 command.go:87: Running command helm with args [delete nginx-v46mkh]

**Comment by yorinasub17** [comment]
Which version of helm are you using? The error "Error: unknown flag: --show-only" suggests that you are using helm 2 instead of helm 3.

Terratest has switched to only supporting helm 3 since https://github.com/gruntwork-io/terratest/releases/tag/v0.25.0, so you will need to lock your go mod to use the release just before that one if you wish to test with helm 2.

**Comment by KNSailaja** [comment]
Thank you @yorinasub17 

I have locked go mod to use release v0.24.2. It works :-)
